# Generated by Django 3.0 on 2022-08-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default='No name', max_length=200, verbose_name='Full name'),
        ),
    ]
