# Generated by Django 3.2 on 2022-09-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_auto_20220809_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default='431EFD#', max_length=200, verbose_name='Full name'),
        ),
    ]
