# Generated by Django 3.0.3 on 2022-08-13 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('isOrdered', models.BooleanField(default=False)),
                ('mode', models.CharField(choices=[('Pick at station', 'Pick at station'), ('Door step pickup', 'Door step pickup')], default='Pick at station', max_length=100)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Kids', 'Kids'), ('Other', 'Other')], max_length=200)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('isInStock', models.BooleanField(default=True)),
                ('isCustomized', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('mobile', models.PositiveIntegerField()),
                ('order_status', models.CharField(choices=[('Working on it', 'Working on it'), ('Completed', 'Completed')], default='Working on it', max_length=200)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.CharField(blank=True, max_length=200, null=True)),
                ('district', models.CharField(blank=True, max_length=200, null=True)),
                ('ward', models.CharField(blank=True, max_length=200, null=True)),
                ('orderId', models.CharField(max_length=200)),
                ('isCompleted', models.BooleanField(default=False)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='addtocart.Cart')),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='images/')),
                ('characterType', models.CharField(max_length=200)),
                ('characterValue', models.CharField(max_length=100)),
                ('image', models.ManyToManyField(to='addtocart.Product')),
            ],
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField()),
                ('subTotal', models.PositiveIntegerField()),
                ('customization', models.TextField(blank=True, null=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addtocart.Cart')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='addtocart.Product')),
            ],
        ),
    ]
