# Generated by Django 3.0.3 on 2022-08-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addtocart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(to='addtocart.Image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='characterType',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='characterValue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
