# Generated by Django 3.0.3 on 2022-08-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addtocart', '0002_auto_20220813_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Watch', 'Watch'), ('Necklace', 'Necklace'), ('Glass', 'Glass'), ('Bracelet', 'Bracelet'), ('Ring', 'Ring'), ('Other', 'Other')], default='OTHERS', max_length=200),
        ),
    ]
