# Generated by Django 3.0.3 on 2022-08-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addtocart', '0003_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Watch', 'Watch'), ('Necklace', 'Necklace'), ('Glass', 'Glass'), ('Bracelet', 'Bracelet'), ('Ring', 'Ring'), ('Other', 'Other')], max_length=200),
        ),
    ]
