# Generated by Django 3.2 on 2022-08-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addtocart', '0008_alter_cartproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Watch & Bracelets', 'Watch & Bracelets'), ('Necklace/Chain', 'Necklace/Chain'), ('Glass', 'Glass'), ('Ring', 'Ring'), ('T-Shirt', 'T-Shirt'), ('Other', 'Other')], max_length=200),
        ),
    ]
