# Generated by Django 3.2 on 2022-09-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addtocart', '0011_alter_cart_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
