# Generated by Django 3.2 on 2022-09-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addtocart', '0012_alter_image_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='selectedSecondPropertyValue',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='amountInStock',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='hasSecondPropertySelection',
            field=models.BooleanField(default=False),
        ),
    ]
