# Generated by Django 3.2 on 2022-09-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addtocart', '0014_alter_product_amountinstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondPropsSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propType', models.CharField(max_length=200)),
                ('propValue', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='secProps',
            field=models.ManyToManyField(blank=True, null=True, to='addtocart.SecondPropsSelection'),
        ),
    ]
