# Generated by Django 3.2 on 2022-09-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addtocart', '0016_alter_product_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='uniqueOrderId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
