# Generated by Django 3.2 on 2022-09-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addtocart', '0017_order_uniqueorderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mobile',
            field=models.CharField(max_length=500),
        ),
    ]
